# Generated by Django 6.0.1 on 2026-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='vendor',
        ),
    ]
