# Generated by Django 6.0.1 on 2026-01-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_vendorprofile_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_name',
            field=models.TextField(max_length=100),
        ),
    ]
